version: "3.9"
services:
  psql:
    image: postgres:13.3
    container_name: psql
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: register
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - ./register_query.sql:/docker-entrypoint-initdb.d/register_query.sql
  client:
    build: ./register_front
    ports:
      - "3000:3000"
    command: npm run dev
    links:
      - api
  api:
    depends_on:
      psql:
        condition: service_healthy
    restart: always
    build: ./register-api
    ports:
    - "3001:3001"
    command: npm run start:dev
    links:
      - psql
    environment:
      PORT: 3001
      BASE_URL: http://localhost:3001
      DATABASE_HOST: psql
      DATABASE_NAME: register
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432

      MAIL_USER: "mail@test.com"
      MAIL_PASSWORD: "pswdtest"
      MAIL_TEMPLATES_DIR: "/src/resources/mail/templates"
